import "./scrollbar.css";
export default function Scrollbar() {

    return (
        <main className="grid grid-cols-2 h-screen p-4">
            <section>
                controller
            </section>
            <section className=" grid grid-cols-1 gap-8">
                <div className="scroll-bar-thin outline outline-ring/50 outline-offset-2 rounded-sm h-60">
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                </div>
                <div className="scroll-bar outline outline-ring/50 outline-offset-2 rounded-sm h-40 flex gap-4 items-center">
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                </div>
                <div className="scroll-bar outline outline-ring/50 outline-offset-2 rounded-sm h-60">
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                    <div>preview</div>
                </div>
            </section>
        </main>
    );
}